#!/bin/bash
set -e

cd component && git pull && cd ..

VERSION=`echo "console.log(require('./package').version)" | node`
script/update_version $VERSION

script/prepublish && script/test && script/standalone

cd component
git commit -am "Version $VERSION"
git tag -a "v$VERSION" -m "Version $VERSION"
git push
git push --tags
