#!/bin/bash

./node_modules/.bin/browserify \
  dist/runtime.js \
  --standalone Hamlet \
  -o component/hamlet-runtime.js

./node_modules/.bin/browserify \
  dist/standalone-full.js \
  --standalone Hamlet \
  -o component/hamlet-full.js
